### ISSUE TITLE
App is showing wrong locking state

### ISSUE THREAD

**Issue by Sternwichtel** [openvehicles/Open-Vehicle-Android#121]
I"m driving a Kia eSoul with the eNiro / Kona Konfiguration. 
In the vehicle overview I noticed the locking indicator to be wrong. 

If the vehicle is locked the indicator is showing an open padlock in red color.
If the vehicle is unlocked the indicator is showing a closed padlock in green color. 
So while the correct color is shown the padlock symbol is inversed.

![Screenshot_2021-01-23-22-31-24-180_com openvehicles OVMS](https://user-images.githubusercontent.com/77901339/105616200-86727f80-5dd5-11eb-8c66-8fb085f43f60.jpg)

**Comment by dexterbg** [comment]
That's not the App's fault. Please post a report to the V3 module Kia development team, that they need to change the lock status interpretation.
