### ISSUE TITLE
Android intent? 

### ISSUE THREAD

**Issue by glynhudson** [openvehicles/Open-Vehicle-Android#132]
Hi, I'm trying to follow the [docs on the wiki](https://github.com/openvehicles/Open-Vehicle-Android/wiki) to use an Android Intent Action to get the ovms android app to send a message to a vehicle to start a custom script. 

I'm using Tasker to send the intent but I'm not having any luck so far, any ideas what I'm doing wrong? I'm also sending a intent with the service password and vehicle ID 

![Screenshot_20211013-005013](https://user-images.githubusercontent.com/758844/137044231-6883f0ab-55a1-40d9-9af5-10794ab034a4.png)

**Comment by dexterbg** [comment]
Glyn, this is really not a Tasker support forum… all I can do is show you the respective Automagic action definition:

```
  <action type="send_broadcast">
    <useDefaultName>false</useDefaultName>
    <name>SetProfil</name>
    <intentAction>com.openvehicles.OVMS.SendCommand</intentAction>
    <categoryListEnabled>false</categoryListEnabled>
    <categoryList>android.intent.category.DEFAULT</categoryList>
    <dataEnabled>false</dataEnabled>
    <data></data>
    <dataTypeEnabled>false</dataTypeEnabled>
    <dataType>text/plain</dataType>
    <explicitComponent>false</explicitComponent>
    <packageName></packageName>
    <className></className>
    <flagList>FLAG_ACTIVITY_NEW_TASK</flagList>
    <extras>putString("sel_vehicleid", "XXXX");
putString("sel_server_password", "XXXX");
putString("msg_command", "7,script eval abrp.send(1)");
</extras>
    <waitForResult>false</waitForResult>
    <accessResultExtras></accessResultExtras>
  </action>
```

From your log it appears Tasker only adds the "msg_command" extra.

**Comment by glynhudson** [comment]
Thanks, this worked great 👍 

![Screenshot_20211102-021750](https://user-images.githubusercontent.com/758844/139776110-b9992bac-bd00-4d82-b244-66136fd8b259.png)
