### ISSUE TITLE
Leaf charging overlay uses Tesla Roadster

### ISSUE THREAD

**Issue by dalathegreat** [openvehicles/Open-Vehicle-Android#133]
I see the files are there for LEAF overlay charging, but the Tesla Roadster one is used so the plug is being incorrectly lit up as one of the back doors.

**Comment by dalathegreat** [comment]
When I run this in emulator it works:
![image](https://user-images.githubusercontent.com/26695010/145990853-15327fc3-b610-40ac-87f3-b3096aaf70c0.png)

But on my real phone it uses the Tesla Roadster overlay :/

**Comment by dexterbg** [comment]
The Leaf overlay was added in commit 2b164d818258cbab7ed10e05b4617fd6525babe1 so hasn't been publically released yet.

I'll do a public release after having merged your i3 images.

**Comment by dalathegreat** [comment]
Super, then this is not a problem! Closing this issue!
