### ISSUE TITLE
ms_v_charge_type->SetValue("type1") shows J1772 type2 in Android app

### ISSUE THREAD

**Issue by kallisti5** [openvehicles/Open-Vehicle-Android#144]
I just noticed that setting "type1" in OVMS for ms_v_charge_type still shows a type2 connector in the app.

It would be interesting to add some logic around "type1  level 1 vs type2 level 2" in the app and render each plug correctly.

**Comment by kallisti5** [comment]
Example:

![photo_2022-11-26_17-51-29](https://user-images.githubusercontent.com/100110/204113145-076cb647-22e0-40da-9040-e4f01302f748.jpg)

**Comment by kallisti5** [comment]
Actually... I just realized this is because I selected the Zoe vehicle.   These images are static.   Would it be beneficial to "standardize" the charge connector icons and render them in the needed locations instead of just templating out the whole vehicle?

**Comment by dexterbg** [comment]
Beneficial in terms of App size if we would replace the existing overlay images, but not beneficial in terms of developer & user contentment then: overlays for some vehicles have been carefully designed to fit the vehicle charge port and facilities.

We could provide a set of default icons for cars without dedicated overlays though.

**Comment by kallisti5** [comment]
Yeah, you're right on this one.   I added some specific overlays for the Bolt EV and it was easy enough.
