### ISSUE TITLE
Notifications don't work on Android 13

### ISSUE THREAD

**Issue by billybednar** [openvehicles/Open-Vehicle-Android#146]
Starting with Android 13, notifications are disabled by default and the [POST_NOTIFICATIONS](https://developer.android.com/develop/ui/views/notifications/notification-permission) runtime permission must be granted for notifications to work. This app targets Android 13 (as of c23b3dbd772bdae7e82601797cd3a71c2623a78c) and does not request this permission, so notifications do not work. As the [permission is not declared](https://github.com/openvehicles/Open-Vehicle-Android/blob/72fae9f4cf431c04796aa0c24ed9830f141e25ca/OpenVehicleApp/src/main/AndroidManifest.xml#L12-L23), it can not be manually granted from app settings nor by using ADB.

**Comment by dexterbg** [comment]
I can only test the fix in an emulator, can you please try on your Android 13 device?

**Comment by billybednar** [comment]
That fixed it.

The behavior when the notification permission is denied doesn't seem ideal, but I'll make a separate issue for that once I play with it a bit more.

**Comment by markwj** [comment]
FYI: A user 'Larry' provides the following link regarding this issue:

https://source.android.com/docs/core/display/notification-perm

**Comment by dexterbg** [comment]
I already published the fix on Google Play yesterday, maybe 'Larry' can test that?
