### ISSUE TITLE
Getting a different car in app

### ISSUE THREAD

**Issue by yusijs** [openvehicles/Open-Vehicle-Android#147]
I'm honestly not sure what is happening, but suddenly the app started showing me the wrong car. Not sure if it's real or not, but I'm able to send commands etc as well which seems a bit sketchy. 

 ![Screenshot_20230110-094358.png](https://user-images.githubusercontent.com/11261560/211503732-8e469cbf-d2b8-4158-942f-2168ac3207bd.png)

![Screenshot_20230110-094340.png](https://user-images.githubusercontent.com/11261560/211503764-8b8551c2-6b3a-4fd2-98e4-244faf499d79.png)

I'm also getting the GPS coords in the app (able to follow the car on the map) which seems dangerous.

**Comment by dexterbg** [comment]
This is a server (perl) issue, not App related. See https://github.com/openvehicles/Open-Vehicle-Server/issues/2

On which server are you, and what is your vehicle ID?

**Comment by yusijs** [comment]
Apologies - I got the correct information via the api, so assumed it was something funky with the app. I'm on dexter-web.de, and the vehicle ID is `ronnielau`

**Comment by dexterbg** [comment]
I've installed an update, please contact me if this happens again.
