### ISSUE TITLE
Missing images Kia Niro EV (MY2023)

### ISSUE THREAD

**Issue by andrejs2** [openvehicles/Open-Vehicle-Android#149]
Hi all!

Is there any chance to get images for new Kia Niro EV (MY2023)?

Thanks!
Regards,
Andrej

**Comment by glynhudson** [comment]
Does OVMS work on the new Kia Niro 2023? 

Here's an example of a pull request to add images, take a look at the files changed it's not too difficult to do yourself: https://github.com/openvehicles/Open-Vehicle-Android/pull/124/

**Comment by andrejs2** [comment]
> Does OVMS work on the new Kia Niro 2023?
> 
> Here's an example of a pull request to add images, take a look at the files changed it's not too difficult to do yourself: #124

Thanks Glyn for the reply and link. I'll certainly try to add images...

About new Niro...it works, not the same as e-Niro, but I get quite a lot of data (metrics). Sending commands don't work (lock, unlock, heating/cooling....), status of locks is reversed, open door indicator works. Tyre pressure is wrong... and the BMS cell monitory doesn't work either.

**Comment by dexterbg** [comment]
We've also got a Wiki page on this: https://github.com/openvehicles/Open-Vehicle-Android/wiki/Adding-Vehicle-Images

**Comment by andrejs2** [comment]
Spent some time figuring out how to use all these to contribute but I'm not keen in programming nor in any work with github. The only thing I managed to find is an image of a black Kia Niro EV (latest model) and compressed it. 

So I will wait till someone skilled bites into this :(.
Thanks for you help anyway.
