### ISSUE TITLE
Possibility to have battery temperature in Nissan Leaf 30 

### ISSUE THREAD

**Issue by cyrelec86** [openvehicles/Open-Vehicle-Android#152]
Hi team, I wanted to know if it was possible to have the battery temperature of the Nissan Leaf 30 directly with the application?
it does not reflect reality at the moment and I will really need it.
thank you in advance to the contributors you make the world move forward 😉

**Comment by dexterbg** [comment]
The App displays the values provided by the car adaption. If the Nissan Leaf adaption does not provide the battery temperature for your Leaf model, you need to open / extend an issue for the module firmware.

Check for existing Leaf issues here, if none applies add your issue:
https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/issues?q=is%3Aissue+is%3Aopen+nissan+leaf

Regards,
Michael
