### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [openvehicles/Open-Vehicle-Android#157]
Hello!

I found this project from https://hackaday.com/2024/01/25/open-vehicle-monitoring-system-is-the-window-to-your-evs-soul/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by dexterbg** [comment]
This is a sub project of https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3 so shares the same license, but you're right, each repository should have one. I'll add it.

**Comment by vazhnov** [comment]
MIT license — great!
Thank you!
