### ISSUE TITLE
4.1.2 crash after changing vehicle image

### ISSUE THREAD

**Issue by Ironhydroxide** [openvehicles/Open-Vehicle-Android#159]
App Crashes after changing Car Image to anything but the Tesla Roadster.  Then crashes on every subsequent opening of the app. 
Uninstall/Reinstall is the only way to get the app to function after changing image (loads default Tesla Roadster image) 

this occurs on the Demo Car as well as any car added Not the Demo Car.
Crash occurs just after clicking the "save settings" button. 

App: version 4.1.2 (2023010701)
Phone: Pixel 5, /e/OS Version 1.17-t-20231109350751-stable-redfin
Installed from /e/OS App Lounge version 2.6.6

**Comment by dexterbg** [comment]
Crashes occurring on /e/OS but not on Android are most probably related to /e/OS being not fully Android compatible yet.

You're welcome to work on /e/OS compatibility or introduce an /e/OS developer to our team, if you know one.
