### ISSUE TITLE
Temperature and Distance units selection

### ISSUE THREAD

**Issue by markwj** [openvehicles/Open-Vehicle-Android#32]
Implement a selection fo temperature and distance units (like the iOS App).

**Comment by Saftwerk** [comment]
Hello,
in the latest version 3.12.3 is the value of the odometer wrong:
![screenshot wrong odo](https://user-images.githubusercontent.com/19615255/34645829-cb41a21c-f357-11e7-80f9-fa446787cf8d.png)

**Comment by dexterbg** [comment]
I think your module is configured to a wrong distance unit. Please check if parameter #2 is configured to "K" for kilometers or "M" for miles. Note the single upper case letter. If the module is configured to i.e. "Miles", it will still output miles, but the App will not understand the unit code. That would produce the effect shown in your screenshot.

**Comment by Saftwerk** [comment]
Hello, just a small update:
Parameter #2 is indeed a single letter K (and no spaces in front or behind)
But the App shows the value as miles (new screenshots below)

Here some version numbers:
Server 2.1.1-20121216
Car 2.6.5/TR/V2
App 3.12.3 (20180106)
![screenshot_20180309-211535](https://user-images.githubusercontent.com/19615255/37228334-88edd188-23e0-11e8-8b98-22cb4a3c224a.png)
![screenshot_20180309-211558](https://user-images.githubusercontent.com/19615255/37228340-8b1c69f6-23e0-11e8-9064-7c76404a3d4c.png)

Kind regards
Saftwerk

**Comment by dexterbg** [comment]
The App does not convert mi/km, the module does. I don't think this is an App issue, I assume SMS/text command "STAT" also shows miles.

Your module firmware is a bit outdated, but I don't remember any conversion issues…

OK, I checked the firmware code: you currently need to restart the module after changing the units (bug). Can you try that?
