### ISSUE TITLE
Odometer on car frame shows miles

### ISSUE THREAD

**Issue by jilleberends** [openvehicles/Open-Vehicle-Android#45]
The car frame shows 49380km, while in reality my odometer is 79309km. It looks like it is showing the mileage instead.

**Comment by dexterbg** [comment]
You need to update the module firmware, see
https://github.com/openvehicles/Open-Vehicle-Monitoring-System/commit/0cc1d26d1e800d5d21d8e6bc93ab44fb48257c0a

**Comment by jilleberends** [comment]
my bad! :) retested with new firmware, fixed.
