### ISSUE TITLE
Graphic for Nissan e-NV200

### ISSUE THREAD

**Issue by glynhudson** [openvehicles/Open-Vehicle-Android#61]
I'm successfully using the OVSM connected to my e-NV200 Nissan EV van. It uses the same EV electronics as a Leaf. All works great, however the OVSM app does not have a graphic for the e-NV200. I will try and contribute a graphic. Any tips on how the graphics are generated?

I will try and copy the graphics currently in use and create one for the e-NV200 https://github.com/openvehicles/Open-Vehicle-Android/tree/master/OpenVehicleApp/src/main/res/drawable-nodpi

![nissan-e-nv200](https://user-images.githubusercontent.com/758844/43497361-a7c229ea-9539-11e8-9728-f9d3b1879bc9.jpg)

**Comment by dexterbg** [comment]
Go ahead. You need to provide:
- at least one car_<type>_<color>.png for the main/battery page
- at least one ol_car_<type>_<color>.png for the car info page
- optionally: overlays for the ol_car image to signal charging / open doors / … (see ol_car_twizy_chargeport.png for an example)
- at least one map_car_<type>_<color>.png icon for the map and notifications

Note: the images won't be used automatically, they need to be added to the modules.
Note 2: there's an open todo to separate these image sets from the app…

**Comment by glynhudson** [comment]
Thanks for the guidence, very useful. I've made some progress: 

I've got a 'car' graphic of the env200 up and running 

https://github.com/glynhudson/Open-Vehicle-Android/commit/a720cfa3f3e91e3d4f00ba365f643dc68abe35fc

However when I select it the app crashes. This is paresumably since the top down view and the map view are missing. My plan was to use the leaf top-down graphic and map icon since the env200 and white leaf look the same from above! Where is the referance to tell the app to use the top-down view from the leaf?  

![screenshot_20180809-022354](https://user-images.githubusercontent.com/758844/43872900-efe0867a-9b7b-11e8-96c6-2edcb19eca29.png)

**Comment by glynhudson** [comment]
Ok, I just duplicated and renamed the leaf graphics and it's working now  :+1: 

PR submitted https://github.com/openvehicles/Open-Vehicle-Android/pull/65

![screenshot_20180809-024109](https://user-images.githubusercontent.com/758844/43873425-79e24780-9b7e-11e8-84a4-72e2006cc2f3.png)
