### ISSUE TITLE
e-Niro charge amps on new row.

### ISSUE THREAD

**Issue by Timopen** [openvehicles/Open-Vehicle-Android#74]
When charging over 100 A the amps are moved to a new row and no longer visible.
![ovms](https://user-images.githubusercontent.com/29919799/57300145-7af99500-70d6-11e9-84d2-b42a49d2670d.JPG)

**Comment by glynhudson** [comment]
This should be an easy fix, I'll try and take a look. Would you mind posting a non annotated screenshot of the Kia eNiro rapid charging? Would you mind if I used this screenshot for a flyer for OVMS that I'm making? 

I'm currently using a leaf (my car) as the main car, however I would like to change this to be a eNiro but it would look silly to show a eNiro graphic with the estimated range of my leaf! A real eNiro screenshot would be amazing. Hope you're enjoying it, it looks like a fantastic car from everything I've read. 

![OVMS-leaf](https://user-images.githubusercontent.com/758844/58598467-77d86b80-8274-11e9-9d5c-f06c11c926dc.png)

**Comment by Timopen** [comment]
Hi Glyn
I don't have a picture without annotation, but I promise I will take one next time I fast charge. I can use the Ionity charger nearby and we might have Amps near 200 in the picture. Meanwhile here is a slow charge picture.
![Screenshot (10 apr  2019 19_37_32)](https://user-images.githubusercontent.com/29919799/58615730-176d1c80-82bc-11e9-93e1-94de9021ea7b.jpg)
And overview:
![Screenshot (10 apr  2019 19_58_28)](https://user-images.githubusercontent.com/29919799/58615782-3bc8f900-82bc-11e9-8294-37bc47bf2e3d.jpg)

**Comment by glynhudson** [comment]
Thanks, that's great. Does climate control pre heating / cooling work on eNiro for you?

**Comment by glynhudson** [comment]
Climate control my require using home link 1 to activate

**Comment by Timopen** [comment]
No preheating/cooling on the KIA's yet.

**Comment by glynhudson** [comment]
Thanks, that's good to know. Is it not even on the Soul? I thought pre heating was working on the Soul?

**Comment by Timopen** [comment]
No, not on Soul either. The info on shop.openenergymonitor.com is a bit missleading at the moment.

**Comment by glynhudson** [comment]
Thanks, apologies for the confusion. It's now been fixed. Thanks for your help.

https://shop.openenergymonitor.com/open-vehicle-monitoring-ovms-wifi-3g-europe/

**Comment by glynhudson** [comment]
What about TPMS, ODO, speed display (km/h) and door unlocking? Are these features supported on the eNiro? I believe these features are supported on the Soul

**Comment by Timopen** [comment]
All the above exept speed is working. I'm going to try to fix the speed eventually, it shows a bit strange values at the moment. How is the fix for the amps on the same row in the app going?

**Comment by glynhudson** [comment]
@Timopen thanks, that's very useful.

I've attempted to fix the text wrapping by enlarging the text box. However, I have been unable to recreate the text wrapping issue on my device (pixel 2). What device are you using? What is the screen width? 

https://github.com/openvehicles/Open-Vehicle-Android/pull/76

**Comment by Timopen** [comment]
Glyn
I'm using a Oneplus 6T 2340 x 1080 pixels 402 ppi Android 9 Pie.
When usin my old phone Sony xperia 1080 x 1920 pixels, 16:9 ratio (~424 ppi density) Android 8 Oreo there is no wrap.
Oneplus:
![Screenshot_20190614-143121](https://user-images.githubusercontent.com/29919799/59554199-9aba8d80-8f9f-11e9-81db-94c49b70ca80.jpg)

**Comment by Timopen** [comment]
Sony:
![Screenshot_20190614-143106](https://user-images.githubusercontent.com/29919799/59554204-aefe8a80-8f9f-11e9-9c46-2e48e8eb97ce.png)

**Comment by Timopen** [comment]
Hi Glyn
I noticed on the open energy monitor site, there is a selection for KIA OBD2 cable.
This should read KIA Soul OBD2 cable as the e-Niro uses the generic one.

Med Vänlig Hälsning

TIMO PENTTILÄ

**Comment by glynhudson** [comment]
@timopen thanks for letting me know. I will correct the listing and update docs.

**Comment by glynhudson** [comment]
>This should read KIA Soul OBD2 cable as the e-Niro uses the generic one.

@Timopen do you know if the Kia Niro required 'left' or 'right' generic OBD2 cable? Or would either fit
