### ISSUE TITLE
Battery=0 ! + Climate control/AC doesn't actually work

### ISSUE THREAD

**Issue by amralomari** [openvehicles/Open-Vehicle-Android#77]
Dear
in the last 2 days, the app is showing the battery % as Zero (as shown below)

Also, Climate control/AC doesn't actually work; it shows the toast message "OK" but nothing runs in the car.

Location works alright 

![WhatsApp Image 2019-06-25 at 3 40 49 PM](https://user-images.githubusercontent.com/10144617/60099351-1f579980-9760-11e9-8a5b-af01bafa5509.jpeg)

**Comment by dexterbg** [comment]
That's no App issue. Check your server connections. Check the manual and ask the Leaf maintainer about climate control availability for your model.
