### ISSUE TITLE
Colour of white roadster image is too silver

### ISSUE THREAD

**Issue by markwj** [openvehicles/Open-Vehicle-Android#88]
The colour of the white roadster image is too silver. Same issue in the iOS App, so can be resolved together.

**Comment by dexterbg** [comment]
Mark, I tried to lighten up the image for the next Android release. Unfortunately that also affects the rims, so we can't go full white. I haven't committed that version yet, can you please have a look:
![car_roadster_arcticwhite](https://user-images.githubusercontent.com/2706753/69918169-efc75e80-146e-11ea-833f-4c4d73eb344b.png)

**Comment by dexterbg** [comment]
Solved in release 3.14.0
