### ISSUE TITLE
Headlight ON image overlay should be reversed on Leaf right side

### ISSUE THREAD

**Issue by dalathegreat** [openvehicles/Open-Vehicle-Android#92]
![image](https://user-images.githubusercontent.com/26695010/70862405-a84bd280-1f44-11ea-9caa-5a93278e6f3d.png)
The yellow right hand side overlay should be mirror imaged

**Comment by dalathegreat** [comment]
On second thought, maybe it shouldn't? If it's made to represent the light pattern emitted by the headlights (more goes toward shrubbery and not the oncoming traffic)

**Comment by dexterbg** [comment]
Feel free to submit car specific overlay images :D

**Comment by dalathegreat** [comment]
Closing as this was implemented in 3.15.0 👍
